### ISSUE TITLE
initial experiment

### ISSUE THREAD

**Issue by tofutim** [yy502/inkscape-laserpecker#11]
In my initial attempt I got

![image](https://user-images.githubusercontent.com/157766/179860144-7ad014b4-d7a5-490f-9beb-76180e8acf82.png)

I know the svg target size is probably too big, so I will adjust. But this error seems cryptic
![wages](https://user-images.githubusercontent.com/157766/179860201-90e416e5-1ae5-4baf-a10e-11b4a8cd1606.svg)
.

**Comment by yy502** [comment]
hi there,

thanks for reporting this issue. I believe it's because your SVG file was generated using another tool without viewport dimension. The workaround is to open your SVG file in Inkscape, create a new blank file and then copy & paste your design over.

Please let me know if this works.

Cheers.
